whladmin/WHLAdmin/ViewModels/AmiConfigViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using WHLAdmin.Common.Models;

namespace WHLAdmin.ViewModels;

[ExcludeFromCodeCoverage]
public class AmiConfigViewModel : AmiConfig
{
    public List<AmiHhPctAmt> HhPctAmts { get; set; }
}

[ExcludeFromCodeCoverage]
public class EditableAmiConfigViewModel
{
    [Display(Name = "Effective Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "Effective Date is required")]
    [MaxLength(10)]
    public string EffectiveDate { get; set; }

    [Display(Name = "Effective Year")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "Effective Year is required")]
    public int EffectiveYear { get; set; }

    [Display(Name = "4P Household AMI")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "4 Person Household AMI is required")]
    public long IncomeAmt { get; set; }

    public List<AmiHhPctAmt> HhPctAmts { get; set; }

    [Display(Name = "Active")]
    public bool Active { get; set; }
    public string Mode { get; set; }
}

[ExcludeFromCodeCoverage]
public class AmiHhPctAmt
{
    public int Size { get; set ;}
    public int Pct { get; set ;}
    public long Amt { get; set ;}
}

[ExcludeFromCodeCoverage]
public class AmiConfigsViewModel
{
    public IEnumerable<AmiConfigViewModel> Amis { get; set; }
    public bool CanEdit { get; set; }
}

whladmin/WHLAdmin/Controllers/AmiConfigsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHLAdmin.Common.Filters;
using WHLAdmin.Common.Services;
using WHLAdmin.Services;
using WHLAdmin.ViewModels;

namespace WHLAdmin.Controllers;

public class AmiConfigsController : Controller
{
    private readonly ILogger<AmiConfigsController> _logger;
    private readonly IAmiConfigsService _amiConfigsService;
    private readonly IMessageService _messageService;

    public AmiConfigsController(ILogger<AmiConfigsController> logger, IAmiConfigsService amiConfigsService, IMessageService messageService)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _amiConfigsService = amiConfigsService ?? throw new ArgumentNullException(nameof(amiConfigsService));
        _messageService = messageService ?? throw new ArgumentNullException(nameof(messageService));
    }

    [HttpGet]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,OPSVIEWER,LOTADMIN,LOTVIEWER")]
    public async Task<IActionResult> Index([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _amiConfigsService.GetData(requestId, correlationId, username);
            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpGet]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,LOTADMIN")]
    public IActionResult Add([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = _amiConfigsService.GetOneForAdd();
            return PartialView("_AMIConfigEditor", model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return PartialView("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,LOTADMIN")]
    public async Task<IActionResult> Add([FromHeader] string username, [FromForm] EditableAmiConfigViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var returnCode = await _amiConfigsService.Add(correlationId, username, model);
            if (returnCode.Length > 0)
            {
                return BadRequest(new ErrorViewModel
                {
                    Code = returnCode,
                    Message = _messageService.GetMessage(returnCode),
                    RequestId = requestId
                });
            }
            return Ok(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return StatusCode(500, new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpGet]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,LOTADMIN")]
    public async Task<IActionResult> Edit([FromHeader] string username, [FromQuery] int effectiveDate)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _amiConfigsService.GetOneForEdit(effectiveDate);
            if (model == null)
            {
                return NotFound();
            }
            return PartialView("_AMIConfigEditor", model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return PartialView("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,LOTADMIN")]
    public async Task<IActionResult> Edit([FromHeader] string username, [FromForm] EditableAmiConfigViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var returnCode = await _amiConfigsService.Update(correlationId, username, model);
            if (returnCode.Length > 0)
            {
                return BadRequest(new ErrorViewModel
                {
                    Code = returnCode,
                    Message = _messageService.GetMessage(returnCode),
                    RequestId = requestId
                });
            }
            return Ok(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return StatusCode(500, new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,LOTADMIN")]
    public async Task<IActionResult> Delete([FromHeader] string username, [FromQuery] int amiId)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var returnCode = await _amiConfigsService.Delete(correlationId, username, amiId);
            if (returnCode.Length > 0)
            {
                return BadRequest(new ErrorViewModel
                {
                    Code = returnCode,
                    Message = _messageService.GetMessage(returnCode),
                    RequestId = requestId
                });
            }
            return Ok();
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return StatusCode(500, new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }
}

whladmin/WHLAdmin/Controllers/AuditController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHLAdmin.Common.Filters;
using WHLAdmin.Services;
using WHLAdmin.ViewModels;

namespace WHLAdmin.Controllers;

[AdminRoleAuthorize("SYSADMIN,OPSADMIN,OPSVIEWER,LOTADMIN,LOTVIEWER")]
public class AuditController : Controller
{
    private readonly ILogger<AuditController> _logger;
    private readonly IAuditService _auditService;

    public AuditController(ILogger<AuditController> logger, IAuditService auditService)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _auditService = auditService ?? throw new ArgumentNullException(nameof(auditService));
    }

    [HttpGet]
    [AdminRoleAuthorize("")]
    public async Task<IActionResult> Index([FromHeader] string username, [FromQuery] string entityType, [FromQuery] string entityId)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _auditService.GetData(entityType, entityId);
            return PartialView(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return PartialView("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }
}

whladmin/WHLAdmin/Views/AmiConfigs/Index.cshtml
@model AmiConfigsViewModel
@{
  ViewData["Title"] = "AMIs";
  var amisCount = Model.Amis?.Count() ?? 0;
}

<div class="row">
  <div class="col-xs-12 col-md-9">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a class="whl-link" asp-area="" asp-controller="Home" asp-action="Index"
            title="Home"><small><i class="fa-solid fa-house"></i></small></a></li>
        <li class="breadcrumb-item"><small>Admin Site</small></li>
        <li class="breadcrumb-item active fs-6 fw-bolder" aria-current="page"><small>@ViewData["Title"]</small></li>
      </ol>
    </nav>
  </div>
  <div class="col-xs-12 col-md-3 text-end">
    <button type="button" class="btn btn-sm btn-link whl-link mr-4 whl-action-refresh-page" title="Refresh"
      aria-label="Refresh"><i class="fa-solid fa-rotate-right"></i></button>
  </div>
</div>

<div class="text-left mt-8">
  <div class="card bg-light">
    <table class="table table-sm table-hover">
      <thead class="bg-whlgreen text-white">
        <tr>
          <th class="text-center" style="width: 120px;">
            <small>
              @if (Model.CanEdit)
              {
                <a class="whl-link text-white fw-bold whl-action-add-ami" title="Add a new AMI"
                  href="javascript:void(0);"><i class="fa-solid fa-plus"></i>&nbsp;Add</a>
              }
            </small>
          </th>
          <th class="text-center"><small>Effective Date</small></th>
          <th class="text-center"><small>4P HH AMI ($)</small></th>
          <th class="text-center"><small>1P HH</small></th>
          <th class="text-center"><small>2P HH</small></th>
          <th class="text-center"><small>3P HH</small></th>
          <th class="text-center"><small>4P HH</small></th>
          <th class="text-center"><small>5P HH</small></th>
          <th class="text-center"><small>6P HH</small></th>
          <th class="text-center"><small>7P HH</small></th>
          <th class="text-center"><small>8P HH</small></th>
          <th class="text-center"><small>9P HH</small></th>
          <th class="text-center"><small>10P HH</small></th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        @if (amisCount == 0)
        {
          <tr>
            <td colspan="13" class="text-center">No AMIs found</td>
          </tr>
        }
        else
        {
          foreach (var ami in Model.Amis.OrderByDescending(o => o.EffectiveDate))
          {
            <tr>
              <td class="text-center" style="width: 120px;">
                <small>
                  @if (Model.CanEdit)
                  {
                    <a class="whl-link whl-action-edit-ami" data-amiid="@ami.EffectiveDate" title="Edit AMI"
                      href="javascript:void(0);"><i class="fa-solid fa-pencil"></i></a>
                    @* <a class="whl-link whl-action-delete-ami ml-8" data-amiid="@amenity.EffectiveDate" title="Delete AMI"
                        href="javascript:void(0);"><i class="fa-solid fa-trash"></i></a> *@
                  }
                  <a class="whl-link whl-action-view-audit ml-8" data-entitytype="AMI"
                    data-entityid="@ami.EffectiveDate" title="View audit log" href="javascript:void(0);"><i
                      class="fa-solid fa-list"></i></a>
                </small>
              </td>
              <td class="text-center"><small>@ami.EffectiveDate.ToString().Insert(6, "-").Insert(4, "-")</small></td>
              <td class="text-center"><small>@ami.IncomeAmt.ToString("C0")</small></td>
              @for (var hhSizeCtr = 0; hhSizeCtr < 10; hhSizeCtr++)
              {
                <td class="text-center">
                  <small>@ami.HhPctAmts[hhSizeCtr].Pct%</small><br />
                  <small class="badge bg-whlgreen text-white mt-8">@ami.HhPctAmts[hhSizeCtr].Amt.ToString("C0")</small>
                </td>
              }
            </tr>
          }
        }
      </tbody>
    </table>
  </div>
</div>

<!-- Ami Editor Modal -->
<div class="modal fade" id="amiEditorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="amiEditorModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="amiEditorModalLabel"><span id="whl-title-ami-action">AMI Editor</span></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <input type="hidden" id="hidAmiAction" name="hidAmiAction" value="" />
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i
            class="fa-solid fa-ban"></i>&nbsp;Cancel</button>
        <button type="button" class="btn btn-primary whl-action-save-ami"><i
            class="fa-solid fa-floppy-disk"></i>&nbsp;Save</button>
      </div>
    </div>
  </div>
</div>

<!-- Audit Viewer Modal -->
@await Html.PartialAsync("~/Views/Shared/_AuditViewerModalPartial.cshtml")

@section Scripts
{
  <script>
    //<![CDATA[
    const amiConfigAddUrl = '@Url.Action("Add", "AmiConfigs")';
    const amiConfigEditUrl = '@Url.Action("Edit", "AmiConfigs")';
    const amiConfigDeleteUrl = '@Url.Action("Delete", "AmiConfigs")';
    const auditViewerUrl = '@Url.Action("Index", "Audit")';
    //]]>
  </script>
  <script src="~/js/management/common.js" asp-append-version="true"></script>
  <script src="~/js/management/amiconfigs.js" asp-append-version="true"></script>
}

whladmin/WHLAdmin/Views/AmiConfigs/_AMIConfigEditor.cshtml
@model EditableAmiConfigViewModel

<div class="text-left">
  @using (Html.BeginForm("Add", "AMIConfigs", FormMethod.Post))
  {
    <div id="divSaveErrorMessage" style="display: none;">
      <h6 class="text-danger"><i class="fa-solid fa-triangle-exclamation"></i>&nbsp;Error</h6>
      <p id="lblSaveErrorMessage">Failed to save AMI information</p>
      <hr />
    </div>

    <input type="hidden" asp-for="EffectiveYear" value="@Model.EffectiveYear" class="whl-formfield-effectiveyear" />
    <input type="hidden" asp-for="Mode" value="@Model.Mode" class="whl-formfield-mode" />

    <div class="row mb-3">
      <div class="col-xs-12 col-md-6">
        <label class="form-label small fw-bolder" asp-for="EffectiveDate">Effective Date <span class="text-danger">*</span></label><br />
        @if (Model.Mode == "ADD")
        {
          <input type="date" class="form-control form-control-sm whl-formfield-effectivedate" placeholder="MM/dd/yyyy" maxlength="10" asp-for="EffectiveDate" />
        }
        else
        {
          <input type="text" name="EffectiveDate" id="EffectiveDate" value="@Model.EffectiveDate" class="form-control whl-formfield-effectivedate" disabled="disabled" />
        }
      </div>
      <div class="col-xs-12 col-md-6">
        <label class="form-label small fw-bolder" asp-for="IncomeAmt">4P Household AMI <span class="text-danger">*</span></label><br />
        <div class="input-group input-group-sm">
          <span class="input-group-text">$</span>
          <input type="text" class="form-control form-control-sm whl-formfield-numeric whl-formfield-incomeamt" placeholder="Enter Income Amount" maxlength="9" asp-for="IncomeAmt" />
        </div>
      </div>
    </div>

    <hr />

    @for (var hhSizeCtr = 0; hhSizeCtr < 10; hhSizeCtr+=4)
    {
      <div class="row mb-3">
        @for (var colCtr = 0; colCtr < 4; colCtr ++)
        {
          var hhCtr = hhSizeCtr + colCtr;
          if (hhCtr > 9) continue;
          var fieldId = $"Hh{hhCtr + 1}";
          var classId = $"whl-formfield-hh{hhCtr + 1}";
          var fieldLabel = $"{hhCtr + 1}P Household";
          var labelId = $"whl-label-hh{hhCtr + 1}";
          <div class="col-xs-12 col-md-3">
            <label class="form-label small fw-bolder" for="@fieldId">@fieldLabel <span class="text-danger">*</span></label><br />
            <div class="input-group input-group-sm">
              <input type="text" class="form-control form-control-sm whl-formfield-numeric whl-formfield-hh @classId" name="@fieldId" id="@fieldId" value="@Model.HhPctAmts[hhCtr].Pct" maxlength="3" placeholder="Enter %" />
              <span class="input-group-text">%</span>
            </div>
            <small class="badge bg-light text-dark fw-semibold @labelId mt-8">@Model.HhPctAmts[hhCtr].Amt.ToString("C0")</small>
          </div>
        }
      </div>
    }

    <div class="row mb-3" style="display: none;">
      <div class="col-xs-12">
        <div class="form-check form-switch">
          <input type="checkbox" class="form-check-input" role="switch" asp-for="Active" />
          <label class="form-check-label small" asp-for="Active">Active</label>
        </div>
      </div>
    </div>
  }
</div>

<script>
  //<![CDATA[
  $(function () {

    // Disable submission
    $('.whl-action-save-faq').attr('disabled', 'disabled');
    fnToggleSaveAMI();

    $('.whl-formfield-effectivedate').on('change', function (e) {
      $(this).removeClass('is-valid');
      $(this).removeClass('is-invalid');
      var v = $(this).val();
      if (v !== undefined && v !== null && v.trim().length > 0) {
        $(this).addClass('is-valid');
        $('.whl-formfield-effectiveyear').val(v.substring(0, 4));
      } else {
        $(this).addClass('is-invalid');
      }
      fnToggleSaveAMI();
    });

    $('.whl-formfield-numeric').on('keypress', function (e) {
      var reg = /^\d+$/;
      var k = e.key;
      return reg.test(e.key);
    });

    $('.whl-formfield-incomeamt').on('change', function (e) {
      $(this).removeClass('is-valid');
      $(this).removeClass('is-invalid');
      var v = $(this).val();
      if (v === undefined || v === null || v.trim().length === 0) {
        $(this).val('0');
        v = '0';
      }
      var n = parseInt(v);
      if (!isNaN(n) && n < 999999999) {
        $(this).addClass('is-valid');
      }
      fnCalculateAmiAmounts();
      fnToggleSaveAMI();
    });

    $('.whl-formfield-hh').on('change', function (e) {
      $(this).removeClass('is-valid');
      $(this).removeClass('is-invalid');
      var v = $(this).val();
      if (v === undefined || v === null || v.trim().length === 0) {
        $(this).val('0');
        v = '0';
      }
      var n = parseInt(v);
      if (!isNaN(n)) {
        $(this).addClass('is-valid');
      }
      fnCalculateAmiAmounts();
      fnToggleSaveAMI();
    });

    function fnCalculateAmiAmounts() {
      var ia = $('.whl-formfield-incomeamt').val();
      if (isNaN(parseFloat(ia)) || ia <= 0) return;
      $('.whl-formfield-hh').each((i, el) => {
        var p = $(el).val();
        if (!isNaN(parseInt(p)) && p > 0) {
          var a = Math.trunc(ia * p / 100);
          am = Math.trunc(Math.round(a / 50) * 50);
          $('.whl-label-hh' + (i+1).toString()).html('$' + am);
        }
      });
    }

    function fnToggleSaveAMI() {
      var ed = $('.whl-formfield-effectivedate').val();
      var ti = $('.whl-formfield-effectiveyear').val();
      var ia = $('.whl-formfield-incomeamt').val();
      var ds = $('.whl-formfield-displayorder').val();
      var allowSubmission = (ed !== undefined && ed !== null && ed.trim().length > 0)
                              && (ti !== undefined && ti !== null && ti.trim().length > 0)
                              && (ia !== undefined && ia !== null && ia.trim().length > 0)
                              && (ds !== undefined && ds !== null && !isNaN(parseInt(ds)));
      if (allowSubmission) {
        $('.whl-action-save-faq').removeAttr('disabled');
      }
      else {
        $('.whl-action-save-faq').attr('disabled', 'disabled');
      }
    }
  });
  //]]>
</script>