whladmin/WHLAdmin/ViewModels/ReportViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using WHLAdmin.Common.Models;

namespace WHLAdmin.ViewModels;

[ExcludeFromCodeCoverage]
public class DemographicsReportViewModel : ErrorViewModel
{
    [Display(Name = "From Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "From Date is required")]
    public string FromDate { get; set; }

    [Display(Name = "To Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "To Date is required")]
    public string ToDate { get; set; }

    public bool Searched { get; set; }
    public IEnumerable<ApplicationDemographicRecordViewModel> Data { get; set; }
    public Dictionary<string, string> GenderTypes { get; set; }
    public Dictionary<string, string> RaceTypes { get; set; }
    public Dictionary<string, string> EthnicityTypes { get; set; }
}

[ExcludeFromCodeCoverage]
public class ApplicationDemographicRecordViewModel
{
    public long ListingId { get; set; }
    public string ListingName { get; set; }
    public string ListingTypeCd { get; set; }
    public string ListingTypeDescription { get; set; }
    public int TotalCount { get; set; }
    public Dictionary<string, int> GenderData { get; set; }
    public Dictionary<string, int> RaceData { get; set; }
    public Dictionary<string, int> EthnicityData { get; set; }
}

[ExcludeFromCodeCoverage]
public class RegistrationsSummaryReportViewModel : ErrorViewModel
{
    [Display(Name = "From Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "From Date is required")]
    public string FromDate { get; set; }

    [Display(Name = "To Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "To Date is required")]
    public string ToDate { get; set; }

    public bool Searched { get; set; }
    public int TotalRegistrationsCount { get; set; }
    public int TotalActiveCount { get; set; }
    public int TotalInactiveCount { get; set; }
    public IEnumerable<RegistrationSummaryByCountyRecord> NewYorkData { get; set; }
    public IEnumerable<RegistrationSummaryByStateRecord> OtherStatesData { get; set; }
}

[ExcludeFromCodeCoverage]
public class MarketEvaluationsReportViewModel : ErrorViewModel
{
    [Display(Name = "From Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "From Date is required")]
    public string FromDate { get; set; }

    [Display(Name = "To Date")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "To Date is required")]
    public string ToDate { get; set; }

    [Display(Name = "Listing")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "Listing is required")]
    public long ListingId { get; set; }

    public IEnumerable<ListingViewModel> Listings { get; set; }

    public bool Searched { get; set; }
    public IEnumerable<CategoryCountPercentage> Data { get; set; }
}

whladmin/WHLAdmin/Controllers/ReportsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHLAdmin.Common.Filters;
using WHLAdmin.Common.Services;
using WHLAdmin.Services;
using WHLAdmin.ViewModels;

namespace WHLAdmin.Controllers;

[AdminRoleAuthorize("SYSADMIN,OPSADMIN,OPSVIEWER,LOTADMIN,LOTVIEWER")]
public class ReportsController : Controller
{
    private readonly ILogger<ReportsController> _logger;
    private readonly IReportsService _reportsService;
    private readonly IMessageService _messageService;

    public ReportsController(ILogger<ReportsController> logger, IReportsService reportsService, IMessageService messageService)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _reportsService = reportsService ?? throw new ArgumentNullException(nameof(reportsService));
        _messageService = messageService ?? throw new ArgumentNullException(nameof(messageService));
    }

    [HttpGet]
    public IActionResult DemographicsReport([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = _reportsService.InitializeApplicationDemographicsReport();
            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    public async Task<IActionResult> DemographicsReport([FromHeader] string username, [FromForm] DemographicsReportViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            if (model == null)
            {
                model = _reportsService.InitializeApplicationDemographicsReport();
                return View(model);
            }

            var returnCode = await _reportsService.GetApplicationDemographicsReport(model);
            if (returnCode.Length > 0)
            {
                model.Code = returnCode;
                model.Message = _messageService.GetMessage(returnCode);
                model.RequestId = requestId;
            }

            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpGet]
    public IActionResult RegistrationsReport([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = _reportsService.InitializeRegistrationsSummaryReport();
            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    public async Task<IActionResult> RegistrationsReport([FromHeader] string username, [FromForm] RegistrationsSummaryReportViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            if (model == null)
            {
                model = _reportsService.InitializeRegistrationsSummaryReport();
                return View(model);
            }

            var returnCode = await _reportsService.GetRegistrationsSummaryReport(model);
            if (returnCode.Length > 0)
            {
                model.Code = returnCode;
                model.Message = _messageService.GetMessage(returnCode);
                model.RequestId = requestId;
            }

            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpGet]
    public async Task<IActionResult> MarketEvaluationsReport([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _reportsService.InitializeMarketEvaluationsReport();
            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    public async Task<IActionResult> MarketEvaluationsReport([FromHeader] string username, [FromForm] MarketEvaluationsReportViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            if (model == null)
            {
                model = await _reportsService.InitializeMarketEvaluationsReport();
                return View(model);
            }

            var returnCode = await _reportsService.GetMarketEvaluationsReport(model);
            if (returnCode.Length > 0)
            {
                model.Code = returnCode;
                model.Message = _messageService.GetMessage(returnCode);
                model.RequestId = requestId;
            }

            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }
}

whladmin/WHLAdmin/Views/Reports/DemographicsReport.cshtml
@model DemographicsReportViewModel
@{
  ViewData["Title"] = "Application Demographics Report";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a class="whl-link" asp-area="" asp-controller="Home" asp-action="Index" title="Home"><i
          class="fa-solid fa-house"></i></a></li>
    <li class="breadcrumb-item" aria-current="page">Reports</li>
    <li class="breadcrumb-item active" aria-current="page">Application Demographics Report</li>
  </ol>
</nav>

<div class="text-left mt-32" aria-label="amenity">
  <h5>@ViewData["Title"]</h5>

  <!-- Search Parameters -->
  @using (Html.BeginForm("DemographicsReport", "Reports", FormMethod.Post))
  {
    <div class="card card-light border-0 mb-3 mt-16">
      <div class="card-body">
        <div class="row">
          <div class="col-xs-12 col-md-2">Submissions between:</div>
          <div class="col-xs-12 col-md-3">
            @Html.TextBoxFor(e => e.FromDate, htmlAttributes: new
              {
                @class = "form-control whl-formfield-fromdate",
                placeholder = "From Date",
                @type = "date"
              })
            @Html.ValidationMessageFor(v => v.FromDate)
          </div>
          <div class="col-xs-12 col-md-3">
            @Html.TextBoxFor(e => e.ToDate, htmlAttributes: new
              {
                @class = "form-control whl-formfield-todate",
                placeholder = "To Date",
                @type = "date"
              })
            @Html.ValidationMessageFor(v => v.ToDate)
          </div>
          <div class="col-xs-12 col-md-3">
            <button type="submit" class="btn btn-outline-secondary whl-action-viewreport" title="View Report" aria-label="View Report">View
              Report</button>
          </div>
        </div>
      </div>
    </div>
  }

  <!-- Report Data -->
  @if (Model.Searched)
  {
    var listingTypes = "RENTAL|SALE".Split("|");
    <hr />

    <!-- By Listing Type -->
    foreach (var listingType in listingTypes)
    {
      <h4 class="fs-4 mt-16">@(listingType == "RENTAL" ? "Rental" : "Ownership")</h4>
      <div class="card card-light border-0 mb-3 mt-16">
        <div class="card-body">
          <table class="table table-sm table-striped w-100">
            <thead>
              <tr>
                <th>&nbsp;</th>
                <th class="bg-light">&nbsp;</th>
                <th colspan="@Model.RaceTypes.Count" class="text-center">RACIAL GROUP IDENTIFICATION</th>
                <th colspan="@Model.EthnicityTypes.Count" class="text-center bg-light">ETHNICITY</th>
              </tr>
              <tr>
                <th>Development Name</th>
                <th class="text-end bg-light">Total</th>
                @foreach (var raceType in Model.RaceTypes)
                {
                  <th class="text-end">@raceType.Value</th>
                }
                @foreach (var ethnicityType in Model.EthnicityTypes)
                {
                  <th class="text-end bg-light">@ethnicityType.Value</th>
                }
              </tr>
            </thead>
            <tbody>
              @if ((Model.Data?.Count(c => c.ListingTypeCd == listingType) ?? 0) > 0)
              {
                foreach (var record in Model.Data.Where(w => w.ListingTypeCd == listingType))
                {
                  <tr>
                    <td>@record.ListingName</td>
                    <td class="text-end bg-light">@record.TotalCount</td>
                    @foreach (var raceType in Model.RaceTypes)
                    {
                      <td class="text-end">@(record.RaceData.ContainsKey(raceType.Key) ? record.RaceData[raceType.Key] : 0)</td>
                    }
                    @foreach (var ethnicityType in Model.EthnicityTypes)
                    {
                      <td class="text-end bg-light">@(record.EthnicityData.ContainsKey(ethnicityType.Key) ? record.EthnicityData[ethnicityType.Key] : 0)</td>
                    }
                  </tr>
                }
              }
              else
              {
                <tr>
                  <td colspan="@(Model.RaceTypes.Count + Model.EthnicityTypes.Count + 2)" class="text-center">
                    <small class="text-secondary">No application demographics data for @(listingType == "RENTAL" ? "rentals" : "ownership").</small>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      </div>
    }
  }
</div>

@section Scripts
{
  <script>
    //<![CDATA[

    $(function () {

      fnToggleViewReport();

      $('.whl-formfield-fromdate').on('change', function () {
        fnToggleViewReport();
      });

      $('.whl-formfield-todate').on('change', function () {
        fnToggleViewReport();
      });

      function fnToggleViewReport() {

        $('.whl-action-viewreport').attr('disabled', 'disabled');

        var fs = $('.whl-formfield-fromdate').val().split('-');
        var fd = new Date(parseInt(fs[0]), parseInt(fs[1]) - 1, parseInt(fs[2]));

        var ts = $('.whl-formfield-todate').val().split('-');
        var td = new Date(parseInt(ts[0]), parseInt(ts[1]) - 1, parseInt(ts[2]));

        var m = new Date(2024, 0, 1, 0, 0, 0);
        var t = new Date();

        $('.whl-formfield-fromdate').removeClass('is-valid');
        $('.whl-formfield-fromdate').removeClass('is-invalid');
        if (fd !== undefined && fd !== null && fd >= m && fd <= t) {
          $('.whl-formfield-fromdate').addClass('is-valid');
        } else {
          $('.whl-formfield-fromdate').addClass('is-invalid');
          return;
        }

        $('.whl-formfield-todate').removeClass('is-valid');
        $('.whl-formfield-todate').removeClass('is-invalid');
        if (td !== undefined && td !== null && td >= fd && td <= t) {
          $('.whl-formfield-todate').addClass('is-valid');
        } else {
          $('.whl-formfield-todate').addClass('is-invalid');
          return;
        }

        $('.whl-action-viewreport').removeAttr('disabled');

      }

    });

    //]]>
  </script>
}

whladmin/WHLAdmin/Views/Reports/MarketEvaluationsReport.cshtml
@model MarketEvaluationsReportViewModel
@{
  ViewData["Title"] = "Market Evaluations Report";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a class="whl-link" asp-area="" asp-controller="Home" asp-action="Index" title="Home"><i
          class="fa-solid fa-house"></i></a></li>
    <li class="breadcrumb-item" aria-current="page">Reports</li>
    <li class="breadcrumb-item active" aria-current="page">Market Evaluations Report</li>
  </ol>
</nav>

<div class="text-left mt-32" aria-label="amenity">
  <h5>@ViewData["Title"]</h5>

  <!-- Search Parameters -->
  @using (Html.BeginForm("MarketEvaluationsReport", "Reports", FormMethod.Post))
  {
    <div class="card card-light border-0 mb-3 mt-16">
      <div class="card-body">
        <div class="row mb-3">
          <div class="col-xs-12 col-md-2">Listing:</div>
          <div class="col-xs-12 col-md-10">
            @Html.DropDownListFor(e => e.ListingId, new SelectList(Model.Listings, "ListingId", "Name", Model.ListingId),
                   htmlAttributes: new
                   {
                     @class = "form-select whl-formfield-listingid",
                     placeholder = "Select Listing"
                   })
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-xs-12 col-md-2">Submissions between:</div>
          <div class="col-xs-12 col-md-3">
            @Html.TextBoxFor(e => e.FromDate, htmlAttributes: new
              {
                @class = "form-control whl-formfield-fromdate",
                placeholder = "From Date",
                @type = "date"
              })
            @Html.ValidationMessageFor(v => v.FromDate)
          </div>
          <div class="col-xs-12 col-md-3">
            @Html.TextBoxFor(e => e.ToDate, htmlAttributes: new
              {
                @class = "form-control whl-formfield-todate",
                placeholder = "To Date",
                @type = "date"
              })
            @Html.ValidationMessageFor(v => v.ToDate)
          </div>
          <div class="col-xs-12 col-md-3">
            <button type="submit" class="btn btn-outline-secondary whl-action-viewreport" title="View Report"
              aria-label="View Report">View
              Report</button>
          </div>
        </div>
      </div>
    </div>
  }

  @if (!string.IsNullOrEmpty((Model.Code ?? "").Trim()))
  {
    <div id="divSaveErrorMessage">
      <h6 class="text-danger"><i class="fa-solid fa-triangle-exclamation"></i>&nbsp;Error</h6>
      <p id="lblSaveErrorMessage">@Model.Message</p>
      <hr />
    </div>
  }
  else
  {
    <!-- Report Data -->
    if (Model.Searched)
    {
      var totalAppsCount = Model.Data?.FirstOrDefault(f => f.CategoryCd == "GENERAL" && f.CategoryKey ==
      "TOTAL")?.CategoryCount ?? 0;

      <hr />
      <div class="row mb-3">
        <div class="col-xs-12 col-md-3">
          <small class="border-bottom">Total Applications</small><br />
          <span class="fs-5 fw-semibold text-dark">@totalAppsCount</span>
        </div>
      </div>

      if (totalAppsCount > 0)
      {
        var codes = new string[] { "GENDER", "RACE", "ETHNICITY" };
        <div class="card border-0 mt-32">
          <div class="card-header text-dark">Demographics</div>
          <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
              @foreach (var code in codes)
              {
                <div class="col">
                  <div class="card border-0">
                    <div class="card-body">
                      <h6 class="card-title">@code</h6>
                      <div class="w-100 text-center">
                        <canvas id="@($"chartDemographics{code}")" style="width: 50%;"></canvas>
                      </div>
                      <div class="row mt-16">
                        <div class="col-xs-12 col-md-8"><small class="text-secondary fw-bold border-bottom">Category</small>
                        </div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">Count</small></div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">%</small></div>
                      </div>
                      @foreach (var item in Model.Data?.Where(w => w.CategoryCd.Equals(code,
                     StringComparison.CurrentCultureIgnoreCase)))
                      {
                        <div class="row">
                          <div class="col-xs-12 col-md-8">@item.CategoryDescription</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryCount</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryPercentage%</div>
                        </div>
                      }
                    </div>
                  </div>
                </div>
              }
            </div>
          </div>
        </div>

        codes = new string[] { "AMI" };
        <div class="card border-0 mt-32">
          <div class="card-header text-dark">Calculated % AMI by HH Size</div>
          <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
              @foreach (var code in codes)
              {
                <div class="col">
                  <div class="card border-0">
                    <div class="card-body">
                      @* <h6 class="card-title">@code</h6> *@
                      <div class="row">
                        <div class="col-xs-12 col-md-8"><small class="text-secondary fw-bold border-bottom">Category</small>
                        </div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">Count</small></div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">%</small></div>
                      </div>
                      @foreach (var item in Model.Data?.Where(w => w.CategoryCd == "AMI"))
                      {
                        <div class="row">
                          <div class="col-xs-12 col-md-8">@item.CategoryDescription</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryCount</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryPercentage%</div>
                        </div>
                      }
                    </div>
                  </div>
                </div>
              }
            </div>
          </div>
        </div>

        codes = new string[] { "VOUCHER" };
        <div class="card border-0 mt-32">
          <div class="card-header text-dark">Voucher</div>
          <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
              @foreach (var code in codes)
              {
                <div class="col">
                  <div class="card border-0">
                    <div class="card-body">
                      @* <h6 class="card-title">@code</h6> *@
                      <div class="row">
                        <div class="col-xs-12 col-md-8"><small class="text-secondary fw-bold border-bottom">Category</small>
                        </div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">Count</small></div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">%</small></div>
                      </div>
                      @foreach (var item in Model.Data?.Where(w => w.CategoryCd == "VOUCHER" && w.CategoryKey.Equals(code,
                     StringComparison.CurrentCultureIgnoreCase)))
                      {
                        <div class="row">
                          <div class="col-xs-12 col-md-8">@item.CategoryDescription</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryCount</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryPercentage%</div>
                        </div>
                      }
                    </div>
                  </div>
                </div>
              }
            </div>
          </div>
        </div>

        codes = new string[] { "MOBILITY", "HEARING", "VISION" };
        <div class="card border-0 mt-32">
          <div class="card-header text-dark">Request Adapted Units</div>
          <div class="card-body">
            <div class="row row-cols-1 row-cols-md-3 g-4">
              @foreach (var code in codes)
              {
                <div class="col">
                  <div class="card border-0">
                    <div class="card-body">
                      <h6 class="card-title">@code</h6>
                      <div class="row">
                        <div class="col-xs-12 col-md-8"><small class="text-secondary fw-bold border-bottom">Category</small>
                        </div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">Count</small></div>
                        <div class="col-xs-12 col-md-2 text-center"><small
                            class="text-secondary fw-bold border-bottom">%</small></div>
                      </div>
                      @foreach (var item in Model.Data?.Where(w => w.CategoryCd == "ACCESSIBILITY" && w.CategoryKey.Equals(code,
                     StringComparison.CurrentCultureIgnoreCase)))
                      {
                        <div class="row">
                          <div class="col-xs-12 col-md-8">@item.CategoryDescription</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryCount</div>
                          <div class="col-xs-12 col-md-2 text-center">@item.CategoryPercentage%</div>
                        </div>
                      }
                    </div>
                  </div>
                </div>
              }
            </div>
          </div>
        </div>
      }
    }
  }
</div>

@section Scripts
{
  @if (Model.Searched)
  {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"
      integrity="sha512-ZwR1/gSZM3ai6vCdI+LVF1zSq/5HznD3ZSTk7kajkaj4D292NLuduDCO1c/NT8Id+jE58KYLKT7hXnbtryGmMg=="
      crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <div>
      <script>
        //<![CDATA[
        $(function() {
          const data = {
            gender: [
              { key: 'Male', value: 50 },
              { key: 'Choose not to respond', value: 50 }
            ]
          };

          const myChart = new Chart(
            document.getElementById('chartDemographicsGENDER'),
            {
              type: 'doughnut',
              data: {
                labels: data.gender.map(row => row.key),
                datasets: [
                  {
                    label: 'Applications by Gender',
                    data: data.gender.map(row => row.value)
                  }
                ]
              }
            }
          );
        });
        //]]>
      </script>
    </div>
  }
  <script>
    //<![CDATA[

    $(function () {

      fnToggleViewReport();

      $('.whl-formfield-fromdate').on('change', function () {
        fnToggleViewReport();
      });

      $('.whl-formfield-todate').on('change', function () {
        fnToggleViewReport();
      });

      function fnToggleViewReport() {

        $('.whl-action-viewreport').attr('disabled', 'disabled');

        var fs = $('.whl-formfield-fromdate').val().split('-');
        var fd = new Date(parseInt(fs[0]), parseInt(fs[1]) - 1, parseInt(fs[2]));

        var ts = $('.whl-formfield-todate').val().split('-');
        var td = new Date(parseInt(ts[0]), parseInt(ts[1]) - 1, parseInt(ts[2]));

        var m = new Date(2024, 0, 1, 0, 0, 0);
        var t = new Date();

        $('.whl-formfield-fromdate').removeClass('is-valid');
        $('.whl-formfield-fromdate').removeClass('is-invalid');
        if (fd !== undefined && fd !== null && fd >= m && fd <= t) {
          $('.whl-formfield-fromdate').addClass('is-valid');
        } else {
          $('.whl-formfield-fromdate').addClass('is-invalid');
          return;
        }

        $('.whl-formfield-todate').removeClass('is-valid');
        $('.whl-formfield-todate').removeClass('is-invalid');
        if (td !== undefined && td !== null && td >= fd && td <= t) {
          $('.whl-formfield-todate').addClass('is-valid');
        } else {
          $('.whl-formfield-todate').addClass('is-invalid');
          return;
        }

        $('.whl-action-viewreport').removeAttr('disabled');

      }

    });

    //]]>
  </script>
}