whladmin/WHLAdmin/ViewModels/ResourceConfigViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using WHLAdmin.Common.Models;

namespace WHLAdmin.ViewModels;

[ExcludeFromCodeCoverage]
public class ResourceConfigViewModel : ResourceConfig
{
}

[ExcludeFromCodeCoverage]
public class EditableResourceConfigViewModel
{
    public int ResourceId { get; set; }

    [Display(Name = "Title")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "Title is required")]
    [MaxLength(200)]
    public string Title { get; set; }

    [Display(Name = "Text")]
    [MaxLength(4000)]
    public string Text { get; set; }

    [Display(Name = "Website")]
    [Required(AllowEmptyStrings = false, ErrorMessage = "Website is required")]
    [MaxLength(500)]
    public string Url { get; set; }

    [Display(Name = "Display Order")]
    public int DisplayOrder { get; set; }

    [Display(Name = "Active")]
    public bool Active { get; set; }
}

[ExcludeFromCodeCoverage]
public class ResourceConfigsViewModel
{
    public IEnumerable<ResourceConfigViewModel> Resources { get; set; }
    public bool CanEdit { get; set; }
}

whladmin/WHLAdmin/Controllers/AuditController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHLAdmin.Common.Filters;
using WHLAdmin.Services;
using WHLAdmin.ViewModels;

namespace WHLAdmin.Controllers;

[AdminRoleAuthorize("SYSADMIN,OPSADMIN,OPSVIEWER,LOTADMIN,LOTVIEWER")]
public class AuditController : Controller
{
    private readonly ILogger<AuditController> _logger;
    private readonly IAuditService _auditService;

    public AuditController(ILogger<AuditController> logger, IAuditService auditService)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _auditService = auditService ?? throw new ArgumentNullException(nameof(auditService));
    }

    [HttpGet]
    [AdminRoleAuthorize("")]
    public async Task<IActionResult> Index([FromHeader] string username, [FromQuery] string entityType, [FromQuery] string entityId)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _auditService.GetData(entityType, entityId);
            return PartialView(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return PartialView("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }
}

whladmin/WHLAdmin/Controllers/ResourceConfigsController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WHLAdmin.Common.Filters;
using WHLAdmin.Common.Services;
using WHLAdmin.Services;
using WHLAdmin.ViewModels;

namespace WHLAdmin.Controllers;

public class ResourceConfigsController : Controller
{
    private readonly ILogger<ResourceConfigsController> _logger;
    private readonly IResourceConfigsService _resourceConfigsService;
    private readonly IMessageService _messageService;

    public ResourceConfigsController(ILogger<ResourceConfigsController> logger, IResourceConfigsService resourceConfigsService, IMessageService messageService)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _resourceConfigsService = resourceConfigsService ?? throw new ArgumentNullException(nameof(resourceConfigsService));
        _messageService = messageService ?? throw new ArgumentNullException(nameof(messageService));
    }

    [HttpGet]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN,OPSVIEWER")]
    public async Task<IActionResult> Index([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _resourceConfigsService.GetData(requestId, correlationId, username);
            return View(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return View("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpGet]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN")]
    public IActionResult Add([FromHeader] string username)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = _resourceConfigsService.GetOneForAdd();
            return PartialView("_ResourceConfigEditor", model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return PartialView("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN")]
    public async Task<IActionResult> Add([FromHeader] string username, [FromForm] EditableResourceConfigViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var returnCode = await _resourceConfigsService.Add(correlationId, username, model);
            if (returnCode.Length > 0)
            {
                return BadRequest(new ErrorViewModel
                {
                    Code = returnCode,
                    Message = _messageService.GetMessage(returnCode),
                    RequestId = requestId
                });
            }
            return Ok(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return StatusCode(500, new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpGet]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN")]
    public async Task<IActionResult> Edit([FromHeader] string username, [FromQuery] int resourceId)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var model = await _resourceConfigsService.GetOneForEdit(resourceId);
            if (model == null)
            {
                return NotFound();
            }
            return PartialView("_ResourceConfigEditor", model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return PartialView("Error", new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN")]
    public async Task<IActionResult> Edit([FromHeader] string username, [FromForm] EditableResourceConfigViewModel model)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var returnCode = await _resourceConfigsService.Update(correlationId, username, model);
            if (returnCode.Length > 0)
            {
                return BadRequest(new ErrorViewModel
                {
                    Code = returnCode,
                    Message = _messageService.GetMessage(returnCode),
                    RequestId = requestId
                });
            }
            return Ok(model);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return StatusCode(500, new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }

    [HttpPost]
    [AdminRoleAuthorize("SYSADMIN,OPSADMIN")]
    public async Task<IActionResult> Delete([FromHeader] string username, [FromQuery] int resourceId)
    {
        var correlationId = username ?? Guid.NewGuid().ToString();
        var requestId = Activity.Current?.Id ?? HttpContext?.TraceIdentifier ?? correlationId;
        _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Started");

        try
        {
            var returnCode = await _resourceConfigsService.Delete(correlationId, username, resourceId);
            if (returnCode.Length > 0)
            {
                return BadRequest(new ErrorViewModel
                {
                    Code = returnCode,
                    Message = _messageService.GetMessage(returnCode),
                    RequestId = requestId
                });
            }
            return Ok();
        }
        catch (Exception exception)
        {
            _logger.LogError(exception, $"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Unhandled exception");
            return StatusCode(500, new ErrorViewModel { RequestId = requestId, CorrelationId = correlationId, Code = "EX000", Message = exception.Message, Details = exception.StackTrace });
        }
        finally
        {
            _logger.LogDebug($"RequestId: {requestId}, CorrelationId: {correlationId}, Message: Ended");
        }
    }
}

whladmin/WHLAdmin/Views/ResourceConfigs/Index.cshtml
@model ResourceConfigsViewModel
@{
  ViewData["Title"] = "Resources and Links";
  var resourcesCount = Model.Resources?.Count() ?? 0;
}

<div class="row">
  <div class="col-xs-12 col-md-9">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a class="whl-link" asp-area="" asp-controller="Home" asp-action="Index"
            title="Home"><small><i class="fa-solid fa-house"></i></small></a></li>
        <li class="breadcrumb-item"><small>Public Site</small></li>
        <li class="breadcrumb-item active fs-6 fw-bolder" aria-current="page"><small>@ViewData["Title"]</small></li>
      </ol>
    </nav>
  </div>
  <div class="col-xs-12 col-md-3 text-end">
    @if (Model.CanEdit)
    {
      <button type="button" class="btn btn-sm btn-link whl-link mr-8 whl-action-add-resource" title="Add a new Resource"
        aria-label="Add a new Resource"><i class="fa-solid fa-plus"></i></button>
    }
    <button type="button" class="btn btn-sm btn-link whl-link mr-4 whl-action-refresh-page" title="Refresh"
      aria-label="Refresh"><i class="fa-solid fa-rotate-right"></i></button>
  </div>
</div>

<div class="text-left mt-8">
  @if (resourcesCount > 0)
  {
    foreach (var resource in Model.Resources.OrderBy(o => o.DisplayOrder))
    {
      <div class="card mt-8">
        <div class="card-header">
          <h6>@if (resource.Active)
            {
              <i class="fa-solid fa-circle-dot text-success" title="Resource is active"></i>
            }
                else
            {
              <i class="fa-solid fa-circle-stop text-danger" title="Resource is inactive"></i>
            }
            &nbsp;@($"{resource.DisplayOrder}. {resource.Title}")
          </h6>
        </div>
        <div class="card-body">
          <div class="card-text mb-3">
            <div style="white-space: pre-line;">@resource.Text</div>
            @if (!string.IsNullOrEmpty((resource.Url ?? "").Trim()))
            {
              <p class="mt-16 mb-3"><a class="whl-link" href="@resource.Url" target="_blank"><i class="fa-solid fa-globe"></i>
                  @resource.Url</a></p>
            }
          </div>
          @if (Model.CanEdit)
          {
            <a href="javascript:void(0);" class="whl-link whl-action-edit-resource" data-resourceid="@resource.ResourceId"
              title="Edit Resource"><small><i class="fa-solid fa-pencil"></i>&nbsp;Edit</small></a>
            @* <a href="javascript:void(0);" class="whl-link whl-action-delete-resource ml-4" data-resourceid="@resource.ResourceId" data-resourcetitle="@resource.Title" title="Delete Resource"><i
                class="fa-solid fa-trash"></i>&nbsp;Delete</a> *@
          }
          <a class="whl-link whl-action-view-audit ml-8" data-entitytype="RESOURCE" data-entityid="@resource.ResourceId"
            title="View audit log" href="javascript:void(0);"><small><i class="fa-solid fa-list"></i>&nbsp;View Audit
              Log</small></a>
        </div>
      </div>
    }
  }
  else
  {
    <div class="text-center">No resources found</div>
  }
</div>

<!-- Resource Editor Modal -->
<div class="modal fade" id="resourceEditorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="resourceEditorModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="resourceEditorModalLabel"><span id="whl-title-resource-action">Resource
            Editor</span></h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <input type="hidden" id="hidResourceAction" name="hidResourceAction" value="" />
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i
            class="fa-solid fa-ban"></i>&nbsp;Cancel</button>
        <button type="button" class="btn btn-primary whl-action-save-resource"><i
            class="fa-solid fa-floppy-disk"></i>&nbsp;Save</button>
      </div>
    </div>
  </div>
</div>

<!-- Audit Viewer Modal -->
@await Html.PartialAsync("~/Views/Shared/_AuditViewerModalPartial.cshtml")

@section Scripts
{
  <script>
    //<![CDATA[
    const resourceConfigAddUrl = '@Url.Action("Add", "ResourceConfigs")';
    const resourceConfigEditUrl = '@Url.Action("Edit", "ResourceConfigs")';
    const resourceConfigDeleteUrl = '@Url.Action("Delete", "ResourceConfigs")';
    const auditViewerUrl = '@Url.Action("Index", "Audit")';
    //]]>
  </script>
  <script src="~/js/management/common.js" asp-append-version="true"></script>
  <script src="~/js/management/resourceconfigs.js" asp-append-version="true"></script>
}

whladmin/WHLAdmin/Views/ResourceConfigs/_ResourceConfigEditor.cshtml
@model EditableResourceConfigViewModel

<div class="text-left">
  @using (Html.BeginForm("Add", "ResourceConfigs", FormMethod.Post))
  {
    <div id="divSaveErrorMessage" style="display: none;">
      <h6 class="text-danger"><i class="fa-solid fa-triangle-exclamation"></i>&nbsp;Error</h6>
      <p id="lblSaveErrorMessage">Failed to save Resource information</p>
      <hr />
    </div>

    @Html.HiddenFor(h => h.ResourceId);

    <div class="row mb-3">
      <div class="col-xs-12">
        <label class="form-label small fw-bolder" asp-for="Title">Title <span class="text-danger">*</span></label><br />
        <input type="text" class="form-control form-control-sm whl-formfield-title" placeholder="Enter Title" maxlength="200" asp-for="Title" />
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-xs-12">
        <label class="form-label small" asp-for="Text">Description</label><br />
        <textarea rows="3" class="form-control form-control-sm whl-formfield-text" placeholder="Enter Description" maxlength="500" asp-for="Text"></textarea>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-xs-12">
        <label class="form-label small fw-bolder" asp-for="Url">Website <span class="text-danger">*</span></label><br />
        <input type="text" class="form-control form-control-sm whl-formfield-url" placeholder="Enter Link" maxlength="500" asp-for="Url" />
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-xs-12">
        <label class="form-label small" asp-for="DisplayOrder">Display Order</label><br />
        <input type="text" class="form-control form-control-sm whl-formfield-displayorder" placeholder="Enter Display Order" maxlength="3" asp-for="DisplayOrder" />
      </div>
    </div>

    @if (Model.ResourceId > 0)
    {
      <div class="row mb-3">
        <div class="col-xs-12">
          <div class="form-check form-switch">
            <input type="checkbox" class="form-check-input" role="switch" asp-for="Active" />
            <label class="form-check-label small" asp-for="Active">Active</label>
          </div>
        </div>
      </div>
    }
  }
</div>

<script>
  //<![CDATA[
  $(function () {

    // Disable submission
    $('.whl-action-save-resource').attr('disabled', 'disabled');
    fnToggleSaveResource();

    $('.whl-formfield-title').on('change', function (e) {
      $(this).removeClass('is-valid');
      $(this).removeClass('is-invalid');
      var v = $(this).val();
      if (v !== undefined && v !== null && v.trim().length > 0) {
        $(this).addClass('is-valid');
      } else {
        $(this).addClass('is-invalid');
      }
      fnToggleSaveResource();
    });

    $('.whl-formfield-url').on('change', function (e) {
      $(this).removeClass('is-valid');
      $(this).removeClass('is-invalid');
      var v = $(this).val();
      if (v !== undefined && v !== null && v.trim().length > 0) {
        $(this).addClass('is-valid');
      } else {
        $(this).addClass('is-invalid');
      }
      fnToggleSaveResource();
    });

    $('.whl-formfield-displayorder').on('keypress', function (e) {
      var reg = /^\d+$/;
      var k = e.key;
      return reg.test(e.key);
    });

    $('.whl-formfield-displayorder').on('change', function (e) {
      var reg = /^\d+$/;
      $(this).removeClass('is-valid');
      $(this).removeClass('is-invalid');
      var v = $(this).val();
      if (v === undefined || v == null || v.trim().length == 0) {
        $(this).val('0');
        v = '0';
      }
      var n = parseInt(v);
      if (!isNaN(n)) {
        $(this).addClass('is-valid');
      }
      fnToggleSaveResource();
    });

    function fnToggleSaveResource() {
      var ti = $('.whl-formfield-title').val();
      var tx = $('.whl-formfield-text').val();
      var ur = $('.whl-formfield-url').val();
      var ds = $('.whl-formfield-displayorder').val();
      var allowSubmission = (ti !== undefined && ti !== null && ti.trim().length > 0)
                              && (ur !== undefined && ur !== null && ur.trim().length > 0)
                              && (ds !== undefined && ds !== null && !isNaN(parseInt(ds)));
      if (allowSubmission) {
        $('.whl-action-save-resource').removeAttr('disabled');
      }
      else {
        $('.whl-action-save-resource').attr('disabled', 'disabled');
      }
    }
  });
  //]]>
</script>